apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/ping*.log
      pos_file /var/log/ping.log.pos
      tag ping
      <parse>
        @type regexp
        expression /^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3,9}Z)\s+(?<output>\w+)\s+(?<type>\w)\s+(?<data>.*)$/
        time_key timestamp
        time_format %Y-%m-%dT%H:%M:%S.%N
      </parse>
    </source>

    <filter ping>
      @type parser
      key_name data
      <parse>
        @type json
        time_type string
        time_key @timestamp
        time_format %iso8601
      </parse>
    </filter>

    <source>
      @type tail
      path /var/log/containers/pong*.log
      pos_file /var/log/pong.log.pos
      tag pong
      <parse>
        @type regexp
        expression /^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3,9}Z)\s+(?<output>\w+)\s+(?<type>\w)\s+(?<data>.*)$/
        time_key timestamp
        time_format %Y-%m-%dT%H:%M:%S.%N
      </parse>
    </source>

    <filter pong>
      @type parser
      key_name data
      <parse>
        @type json
        time_type string
        time_key @timestamp
        time_format %iso8601
      </parse>
    </filter>

    <match **>
      @type elasticsearch
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      logstash_format true
    </match>

