apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-vs
spec:
  hosts:
    - "*"
  gateways:
    - grpc-gateway
  http:
  - route:
    - destination:
        port:
           number: 8888 
        host: ping.default.svc.cluster.local
        subset: v1
