apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ping
spec:
  hosts:
  - "*"
  gateways:
  - ping-web
  http:
  - route:
    - destination:
        port:
          number: 8888
        host: ping.default.svc.cluster.local
