apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pong-application
  namespace: argocd
  labels:
    name: pong
spec:
  project: default

  source:
    repoURL: https://github.com/PanagiotisPtr/ping-pong.git
    targetRevision: main
    path: services/pong/deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: ping-pong

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
