name: Pong Service Release Workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - 'services/pong/**'

jobs:
  build-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/pong
          file: ./services/pong/Dockerfile
          platforms: linux/amd64
          push: true
          tags: panagiotisptr/pong:latest, panagiotisptr/pong:${{ steps.vars.outputs.short_sha }}

      - name: Update helm Chart
        working-directory: ./services/pong/deploy
        run: yq eval -i '.appVersion = "${{ steps.vars.outputs.short_sha }}"' Chart.yaml 

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update Helm chart appVersion"
          commit_user_name: GitOps Bot
          commit_user_email: gitops-bot@example.com
          commit_author: GitOps Bot <gitops-bot@panagiotispetridis.com>
          file_pattern: 'services/pong/deploy/Chart.yaml'

  release-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: services/pong
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
